# Generated by Django 5.0.1 on 2024-02-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_librarian_user_alter_librarian_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
